unpackaged/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <label>App Item</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Content Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Content_Item__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/Mobile_Refresh__c.object-meta.xml
<CustomObject>
    <description>Used for Records that are mobilised and only need refreshing. Split by record type.</description>
    <label>Mobile Refresh</label>
    <nameField>
        <displayFormat>MRE-{000000}</displayFormat>
        <label>Mobile Refresh Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Refresh</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <description>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced to only the Profile Menu Items that correspond to the Community Profile</description>
    <inlineHelpText>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced</inlineHelpText>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Dynamic_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_SOQL__c</fullName>
    <label>Dynamic SOQL</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Used for Name - can be applied differently for each Record Type</description>
    <inlineHelpText>Used for Name - can be applied differently for each Record Type</inlineHelpText>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Object_Reference__c.field-meta.xml
<CustomField>
    <fullName>Object_Reference__c</fullName>
    <label>Object Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ContentItemRestrictionTest.cls
@isTest
private class ContentItemRestrictionTest {

    @isTest static void testValidTestingDynamicSOQL() {
      // Create Content Item record
      Content_Item__c ci = new Content_Item__c();
      ci.Status__c = 'Active';
      ci.Available_in_Version__c = 'V001;V002';
      insert ci;
      System.assertNotEquals(null, ci.Id, 'Content Item not created');

      String userName = 'testAdmin@testorg.com';

      // Get profile and create user record
      String profileName = 'System Administrator';
      Profile p = [SELECT Id FROM Profile WHERE Name = :profileName];
      System.assertNotEquals(null, p.Id, profileName + ' profile not found');

      User u = new User(Alias='aucalias', Email='test@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Tester', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId=p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName=userName);

      u.Community_View__c = 'System Administrator';
      insert u;
      System.assertNotEquals(null, u.Id, 'User not created');

      // Create Dynamic SOQL in Mobile Refresh
      Mobile_Refresh__c mr = new Mobile_Refresh__c();
      mr.Name__c = userName;
      mr.Status__c = 'Active';
      mr.Object_Reference__c = 'Content_Item__c';
      mr.Dynamic_SOQL__c = 'SELECT Id FROM Content_Item__c WHERE Status__c = \'Active\' AND Available_in_Version__c INCLUDES (\'V001\')';
      insert mr;
      System.assertNotEquals(null, mr.Id, 'Mobile Refresh not created');

      System.runAs(u) {
        ContentItemRestriction restriction = new ContentItemRestriction();
        Set<id> ids = restriction.returnRestrictedIds('');
      }
    }

    @isTest static void testInvalidTestingDynamicSOQL() {
      String userName = 'testAdmin@testorg.com';

      // Get profile and create user record
      String profileName = 'System Administrator';
      Profile p = [SELECT Id FROM Profile WHERE Name = :profileName];
      System.assertNotEquals(null, p.Id, profileName + ' profile not found');

      User u = new User(Alias='aucalias', Email='test@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Tester', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId=p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName=userName);

      u.Community_View__c = 'System Administrator';
      insert u;
      System.assertNotEquals(null, u.Id, 'User not created');

      // Create Dynamic SOQL (invalid) in Mobile Refresh
      Mobile_Refresh__c mr = new Mobile_Refresh__c();
      mr.Name__c = userName;
      mr.Status__c = 'Active';
      mr.Object_Reference__c = 'Content_Item__c';
      mr.Dynamic_SOQL__c = 'SELECT ???invalid??? FROM Content_Item__c WHERE Status__c = \'Active\'';
      insert mr;
      System.assertNotEquals(null, mr.Id, 'Mobile Refresh not created');

      System.runAs(u) {
        ContentItemRestriction restriction = new ContentItemRestriction();
        Set<id> ids = restriction.returnRestrictedIds('');
      }
    }

    @isTest static void testDefaultDynamicSOQL() {
      // Create Content Item record
      Content_Item__c ci = new Content_Item__c();
      ci.Status__c = 'Active';
      ci.Available_in_Version__c = 'V001;V002';
      insert ci;
      System.assertNotEquals(null, ci.Id, 'Content Item not created');

      ContentItemRestriction restriction = new ContentItemRestriction();
      Set<id> ids = restriction.returnRestrictedIds('');
    }

}