unpackaged/main/default/objects/Community_Items__c/Community_Items__c.object-meta.xml
<CustomObject>
    <label>Community Item</label>
    <nameField>
        <displayFormat>ComID-{00}</displayFormat>
        <label>Community Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Items__c/fields/ALT_Tag__c.field-meta.xml
<CustomField>
    <fullName>ALT_Tag__c</fullName>
    <label>ALT Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Brainshark_9_Digit_Number__c.field-meta.xml
<CustomField>
    <fullName>Brainshark_9_Digit_Number__c</fullName>
    <label>Brainshark 9 Digit Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing collateral</fullName>
            </value>
            <value>
                <fullName>Sales tools</fullName>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Contact us</fullName>
            </value>
            <value>
                <fullName>Internal only</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Topic of Interest / Notices</fullName>
            </value>
            <value>
                <fullName>Tutorial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Brainshark Training</fullName>
            </value>
            <value>
                <fullName>Video box</fullName>
            </value>
            <value>
                <fullName>Publication Library</fullName>
            </value>
            <value>
                <fullName>Featured Video</fullName>
            </value>
            <value>
                <fullName>Featured Item</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Continuing Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ComunityItemTypeTemplate__c/ComunityItemTypeTemplate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Community Item Email Template Map</label>
</CustomObject>

unpackaged/main/default/objects/ComunityItemTypeTemplate__c/fields/CommunityItemRecordType__c.field-meta.xml
<CustomField>
    <fullName>CommunityItemRecordType__c</fullName>
    <label>Community Item RecordType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ComunityItemTypeTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Email Template Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CustomProfilePermissions__c/CustomProfilePermissions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Hub Email Button Permissions</label>
</CustomObject>

unpackaged/main/default/classes/EmailToComunityTypeCon.cls
/***
 * Author : Uday/ Prasannanjaneyulu 
 * Date:  20-MAR-2015
 * Description : 
***/ 
 
global with sharing class EmailToComunityTypeCon {
    
    WebService static string SendNotification(string strID){

      if(strID != '' && strID != null ){
             Community_Items__c    objCom = [select id,Name,Title__c,Type__c,ALT_Tag__c,Brainshark_9_Digit_Number__c,recordtypeid from Community_Items__c where id =: strID limit 1];
              map<string,string> mapProfile = new map<string,string>();
              for(CustomProfilePermissions__c objPro : CustomProfilePermissions__c.getAll().values()){
                  mapProfile.put(objPro.Name,objPro.Name);
              }
                 system.debug('mapProfile::::'+mapProfile);
                 //Profile ProfileName = [select id,Name from profile where id = :userinfo.getProfileId()limit 1];
                 string str = UserInfo.getUserName();
                 //system.debug('ProfileName ::::'+ProfileName );
                      if(mapProfile.get(str) != UserInfo.getUserName()){
                            return 'Fail';
                      }else if(objCom.Type__c  == null){
       
                               return'TypeNO';
                      }else if(objCom.Type__c  != null){
                              Map<string,string> MapTemp = new map<string,string>();
                                 for(ComunityItemTypeTemplate__c objTemp : ComunityItemTypeTemplate__c.getAll().values()){
                                     MapTemp.put(objTemp.CommunityItemRecordType__c,objTemp.Template_Name__c);
                                 }
                                  if(MapTemp.get(objCom.Type__c)  ==  null){
                                       return 'NOTYPE';
                                   } else{
            
                                        return 'Sucess';
                                     }
                              }
                            return null; 
        }
        return null;
    }

}