unpackaged/main/default/objects/Mobile_Refresh__c/Mobile_Refresh__c.object-meta.xml
<CustomObject>
    <description>Used for Records that are mobilised and only need refreshing. Split by record type.</description>
    <label>Mobile Refresh</label>
    <nameField>
        <displayFormat>MRE-{000000}</displayFormat>
        <label>Mobile Refresh Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Refresh</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <description>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced to only the Profile Menu Items that correspond to the Community Profile</description>
    <inlineHelpText>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced</inlineHelpText>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Menu_Item__c.field-meta.xml
<CustomField>
    <fullName>Menu_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to lookup from a Profile Menu Item to a Menu or Sub Menu for the app menu permissions.</description>
    <inlineHelpText>Used to lookup from a Profile Menu Item to a Menu or Sub Menu for the app menu permissions.</inlineHelpText>
    <label>Menu Item</label>
    <referenceTo>Mobile_Refresh__c</referenceTo>
    <relationshipLabel>Profile Menu Items</relationshipLabel>
    <relationshipName>Profile_Menu_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Used to create Products</description>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MobileRefreshRestriction.cls
/**
* @description Class used to restrict data returned to app via mc utils syncMobileTable.
*   To implement in Salesforce:
*     - Create a MobileCaddy 'Support Component' record with field mobilecaddy1__Name__c = MobileRefreshRestriction
*     - On the MobileCaddy 'Mobile Table' record, set field 'Platform Object Support' to record created above
**/
global class MobileRefreshRestriction implements mobilecaddy1.RestrictionInterface001_mc {

  global Set<Id> returnRestrictedIds(String jsonParams) {
    // Get community profile name from the user's User record
    User user = [SELECT Community_View__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];

    // Get all menus
    List<Mobile_Refresh__c> menus = [SELECT Id, Available_in_Version__c
                                     FROM Mobile_Refresh__c
                                     WHERE RecordType.Name IN ('Menu Item', 'Sub Menu Item')
                                     AND Status__c = 'Active'];

    // Determine whether the menus are applicable for the version
    Set<Id> menusToInclude = new Set<Id>();
    for (Mobile_Refresh__c menu : menus) {
        Boolean includeMenu = false;
        if (menu.Available_in_Version__c != null) {
            if (menu.Available_in_Version__c.contains('V001')) {
                includeMenu = true;
            }
        }
        if (includeMenu) {
            menusToInclude.add(menu.Id);
        }
    }

    // Select:
    //  - menu profile items for the user's community profile (and version)
    //  - active products
    //  - active record type references (record type ids for org)
    //  - active lot numbers
    List<Mobile_Refresh__c> queryResults = [SELECT Id
                                            FROM Mobile_Refresh__c
                                            WHERE (RecordType.Name = 'Profile Menu Item'
                                                    AND Profile__c = :user.Community_View__c
                                                    AND Status__c = 'Active'
                                                    AND Menu_Item__c IN :menusToInclude)
                                            OR (RecordType.Name IN ('Product', 'Record Type Reference', 'Lot Numbers')
                                                    AND Status__c = 'Active')
                                            ];

    // Return set of ids
    return (new Map<Id,SObject>(queryResults)).keySet();
  }

}