unpackaged/main/default/objects/Mobile_Refresh__c/Mobile_Refresh__c.object-meta.xml
<CustomObject>
    <description>Used for Records that are mobilised and only need refreshing. Split by record type.</description>
    <label>Mobile Refresh</label>
    <nameField>
        <displayFormat>MRE-{000000}</displayFormat>
        <label>Mobile Refresh Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Refresh</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <description>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced to only the Profile Menu Items that correspond to the Community Profile</description>
    <inlineHelpText>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced</inlineHelpText>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Used for Name - can be applied differently for each Record Type</description>
    <inlineHelpText>Used for Name - can be applied differently for each Record Type</inlineHelpText>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/recordTypes/Menu_Item.recordType-meta.xml
<RecordType>
    <fullName>Menu_Item</fullName>
    <active>true</active>
    <description>Used to create Menu Items</description>
    <label>Menu Item</label>
</RecordType>

unpackaged/main/default/classes/MobileRefreshRestrictionTest.cls
@isTest
private class MobileRefreshRestrictionTest {

    private static void init() {
        // Get Menu Item record type id
        Id menuItemRecordTypeId = getRecordTypeId('Menu_Item',Mobile_Refresh__c.SObjectType);
        System.assertNotEquals(null, menuItemRecordTypeId, 'Cannot find Menu Item record type');

        Mobile_Refresh__c menu1 = new Mobile_Refresh__c(Name__c='Menu Option1',Available_in_Version__c='V001;V002',Status__c='Active',RecordTypeId=menuItemRecordTypeId);
        insert menu1;
        System.assertNotEquals(null, menu1.Id, 'Menu not created');
    }

    @isTest static void testReturnRestrictionIds() {
        init();

        // Start the test
        Test.startTest();

        MobileRefreshRestriction restriction = new MobileRefreshRestriction();
        Set<id> ids = restriction.returnRestrictedIds('');

        // Stop the test
        Test.stopTest();
    }

    /**
     * @description Returns the record type id for a record type developer name
     **/
    private static Id getRecordTypeId(String recordTypeDeveloperName, Schema.SObjectType sObjType) {
        // Get the object name from the sObject parameter
        String sObjectType = sObjType.getDescribe().getName();

        Id returnId = null;
        // Query for record types
        List<RecordType> recordTypes = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = :sObjectType];
        // Check for name match
        for (RecordType rt : recordTypes) {
            if (rt.DeveloperName == recordTypeDeveloperName) {
                returnId = rt.Id;
                break;
            }
        }

        return returnId;
    }

}