unpackaged/main/default/objects/Surgeon_in_Hospital__c/Surgeon_in_Hospital__c.object-meta.xml
<CustomObject>
    <label>Surgeon in Hospital</label>
    <nameField>
        <displayFormat>SH {0000}</displayFormat>
        <label>Surgeon in Hospital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surgeons in Hospital</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeons</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SurgeonInHospitalNonCommunity.cls
public with sharing class SurgeonInHospitalNonCommunity {

  public static Set<Id> returnRestrictedIds() {
    // Get user record so we can check for sys admin
    User user = [SELECT Community_View__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];

    // Get limits from labels
    String surgeonInHospitalAdminLimitLabel = Label.SurgeonInHospitalAdminLimit;
    Integer surgeonInHospitalAdminLimit = isInteger(surgeonInHospitalAdminLimitLabel) ? Integer.ValueOf(surgeonInHospitalAdminLimitLabel) : 2500;
    String surgeonInHospitalStandardUserLimitLabel = Label.SurgeonInHospitalStandardUserLimit;
    Integer surgeonInHospitalStandardUserLimit = isInteger(surgeonInHospitalStandardUserLimitLabel) ? Integer.ValueOf(surgeonInHospitalStandardUserLimitLabel) : 2500;

    // List for query results
    List<Surgeon_in_Hospital__c> queryResults = new List<Surgeon_in_Hospital__c>();

    // If sys admin, then return rows based on limit
    if (user.Community_View__c == 'System Administrator') {
      queryResults = [SELECT Id FROM Surgeon_in_Hospital__c WHERE Hospital__r.Name != NULL LIMIT :surgeonInHospitalAdminLimit];
    } else {
      // Standard user (not sys admin nor community)
      queryResults = [SELECT Id FROM Surgeon_in_Hospital__c WHERE Hospital__r.Name != NULL];

      // Raise an error if more records are to be returned than our limit
      if (queryResults.size() > surgeonInHospitalStandardUserLimit) {
        throw new mobilecaddy1.MC_001_mcException(mobilecaddy1.MC_001_mcException.MC_EXT_CLASS_LIMITS,'SurgeonInHospitalNonCommunity class - more than ' + surgeonInHospitalStandardUserLimit + ' Surgeon_in_Hospital__c records will be returned.');
      }
    }
    // Return the ids for surgeons in hospital with sharing on
  	return (new Map<Id,Surgeon_in_Hospital__c>(queryResults)).keySet();
  } // end returnRestrictedIds

  private static Boolean isInteger(String test) {
    try {
      Integer x = Integer.valueOf(test);
      return true;
    } catch(Exception e) {
      return false;
    }
  }

} // end class