unpackaged/main/default/objects/Account/fields/Account_Alias__c.field-meta.xml
<CustomField>
    <fullName>Account_Alias__c</fullName>
    <inlineHelpText>Enter an alias, or nickname.  This field is used to populate the title of an opportunity.</inlineHelpText>
    <label>Account Alias</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory Custom</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada &amp; South America</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada &amp; South America</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Key_Account_Plan__c/Key_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Top 5 Account Plan</label>
    <nameField>
        <displayFormat>KAP-{000}</displayFormat>
        <label>Top 5 Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Top 5 Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Key_Account_Plan__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Key_Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/Sales_by_year__c.object-meta.xml
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>H-Sales - {000}</displayFormat>
        <label>Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_by_year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q1_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q1_Sales_Actual__c</fullName>
    <label>Current Year Q1 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q1_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q1_Sales_Target__c</fullName>
    <label>Current Year Q1 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q2_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q2_Sales_Actual__c</fullName>
    <label>Current Year Q2 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q2_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q2_Sales_Target__c</fullName>
    <label>Current Year Q2 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q3_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q3_Sales_Actual__c</fullName>
    <label>Current Year Q3 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q3_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q3_Sales_Target__c</fullName>
    <label>Current Year Q3 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q4_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q4_Sales_Actual__c</fullName>
    <label>Current Year Q4 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q4_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q4_Sales_Target__c</fullName>
    <label>Current Year Q4 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/Surgeon_in_Hospital__c.object-meta.xml
<CustomObject>
    <label>Surgeon in Hospital</label>
    <nameField>
        <displayFormat>SH {0000}</displayFormat>
        <label>Surgeon in Hospital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surgeons in Hospital</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeons</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hospitals</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

unpackaged/main/default/classes/AccountPanelsTest.cls
@isTest
public class AccountPanelsTest {
  
    @isTest
    private static void runTest() {
        
        Test.startTest();
        AccountPanelsTest apt = new AccountPanelsTest();
        
        // insert test data
        Account acc = apt.getAccount();
        System.debug(acc);
        insert acc;
        Key_Account_Plan__c kap = apt.getKeyAccountPlan(acc.Id);
        System.debug(kap);
        insert kap;
        Sales_by_year__c sby = apt.getSalesByYear(acc.Id);
        insert sby;
        Contact con = apt.getSurgeon();
        insert con;
        Surgeon_in_Hospital__c sih = apt.getSurgeonInHospital(acc.Id, con.Id);
        insert sih;
        
        // set page parameter
        PageReference page = Page.AccountPanels;
        page.getParameters().put('Id', String.valueOf(kap.Id));
        Test.setCurrentPage(page);
        
        // initiate controller
        ApexPages.StandardController sc = new ApexPages.StandardController(kap);
        AccountPanelsClass apc = new AccountPanelsClass(sc);
        
        System.debug(apc.accountId);
        
        
    }
    
    // create fake account
    public Account getAccount() {
      String recordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Hospital'
        AND SobjectType = 'Account'
      ].Id;
      Account acc = new Account(
        Name = 'Test', 
        Account_Alias__c = 'Test', 
        CurrencyIsoCode = 'GBP', 
        Territory__c = 'International',
        RecordTypeId = recordTypeId
      );
      return acc;
    }
    
    // create fake key account plan
    public Key_Account_Plan__c getKeyAccountPlan(String id) {
      Key_Account_Plan__c kap = new Key_Account_Plan__c(
        Hospital__c = id
      );
      return kap;
    }
    
    //create fake sales
    public Sales_by_year__c getSalesByYear(String id) {
      Sales_by_year__c sby = new Sales_by_year__c(
        Account__c = id,
        Active__c = true,
        CurrencyIsoCode = 'GBP',
        Q1_Sales_Target__c = 10,
        Q2_Sales_Target__c = 10,
        Q3_Sales_Target__c = 10,
        Q4_Sales_Target__c = 10,
        Q1_Sales_Actual__c = 10,
        Q2_Sales_Actual__c = 10,
        Q3_Sales_Actual__c = 10,
        Q4_Sales_Actual__c = 10
      );
      return sby;
    }
    
    // create fake surgeon
    public Contact getSurgeon() {
      Contact con = new Contact(
        LastName = 'Test',
        CurrencyIsoCode = 'GBP',
        Territory__c = 'International'
      );
      return con;
    }
    
    // create fake junction object
    public Surgeon_in_Hospital__c getSurgeonInHospital(String accountId, String contactId) {
      Surgeon_in_Hospital__c sih = new Surgeon_in_Hospital__c(
        Hospital__c = accountId,
        Surgeon__c = contactId
      );
      return sih;
    }
    
}