unpackaged/main/default/objects/Account/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hospitals</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/DOF__c.object-meta.xml
<CustomObject>
    <description>Used for recorrding orders added by the Hub Mobile App</description>
    <label>DOF</label>
    <nameField>
        <displayFormat>DOF-{000000}</displayFormat>
        <label>DOF Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DOF__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of the rep that recorded the order.</inlineHelpText>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DOFs</relationshipLabel>
    <relationshipName>DOFs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Hospital the Surgeon requires the product for.</inlineHelpText>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DOFs (Hospital)</relationshipLabel>
    <relationshipName>DOFs1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/recordTypes/DOF.recordType-meta.xml
<RecordType>
    <fullName>DOF</fullName>
    <active>true</active>
    <label>DOF</label>
</RecordType>

unpackaged/main/default/objects/DOF_Item__c/DOF_Item__c.object-meta.xml
<CustomObject>
    <description>Used for DOF Items added against the parent DOF Item</description>
    <label>DOF Item</label>
    <nameField>
        <displayFormat>DFM-{000000}</displayFormat>
        <label>DOF Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOF Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DOF_Item__c/fields/DOF__c.field-meta.xml
<CustomField>
    <fullName>DOF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to parent DOF</inlineHelpText>
    <label>DOF</label>
    <referenceTo>DOF__c</referenceTo>
    <relationshipLabel>DOF Items</relationshipLabel>
    <relationshipName>DOF_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DOFTemplateController.cls
/**
*	@description : This controller to get the images from the document folder
**/
public without sharing class DOFTemplateController {

	public Id dofId {get; set 	{
									if(dofId == null && value != null){
										this.dofId = value;
										fetchDof();
									}
								}
							}
	public DOF__c dof {get; set;}

	/**
	*	@description : Method to get the base url
	*  	@reurn : Current Org Base Url
	**/
	public String getSalesforceBaseUrl(){
		return System.URL.getSalesforceBaseUrl().toExternalForm();
	}


	/**
	*	@description : Method to fetch the dof record
	**/
	private void fetchDof(){
		List<DOF__c> dofList = (List<Dof__c>)Database.query(buildSoql());

		if(!dofList.isEmpty()){
			this.dof = dofList[0];
		}
	}

	/**
	*	@description : Method to build the soql
	*  	@return String Soql String to query.
	**/
	private String buildSoql(){
		String soqlString = 'SELECT ';
		// get fieldslist
		Set<String> fieldList = new Set<String>();

		// add dof fields 
		fieldList.addAll(SchemaHelper.getAllFieldsForSObject(DOF__c.sObjectType.getDescribe().getName()));

		// get account fields 
		Set<String> accountFieldsList = SchemaHelper.getAllFieldsForSObject(Account.sObjectType.getDescribe().getName());

		// add distributor fields list 
		fieldList.addAll(addParentFieldName(accountFieldsList,DOF__c.Distributor__c.getDescribe().getName().replace('__c','__r')));

		// add hospital fields list 
		fieldList.addAll(addParentFieldName(accountFieldsList,DOF__c.Hospital__c.getDescribe().getName().replace('__c','__r')));

		soqlString += String.join(new List<String>(fieldList),',')+
						',(SELECT '+String.join(new List<String>(SchemaHelper.getAllFieldsForSObject(DOF_Item__c.sObjectType.getDescribe().getName())),',')+' FROM DOF_Items__r)'+
							' FROM '+DOF__c.sObjectType.getDescribe().getName()+' WHERE Id = \''+this.dofId+'\' LIMIT 1';

		return soqlString;
	}


	/**
	*	@description : Method to add the parent field name to the fields list
	*  	@return  Set<String> list of modified fields list
	**/
	private Set<String> addParentFieldName(Set<String> fieldsList, String parentFieldName){
		Set<String> modifiedFieldsList = new Set<String>();

		// add parent field name to the start 
		for(String fieldName : fieldsList){
			modifiedFieldsList.add(parentFieldName+'.'+fieldName);
		}
		return modifiedFieldsList;
	}

}