unpackaged/main/default/objects/Account/fields/Update_date__c.field-meta.xml
<CustomField>
    <fullName>Update_date__c</fullName>
    <label>Update date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToRemoveInactCampMemTest.cls
@isTest
private class BatchToRemoveInactCampMemTest 
{
    static testMethod void testBatch() 
	{
		 Profile p = [SELECT id from profile WHERE name = 'System Administrator'];
		 
		 User u2 = new User (lastname = 'testlast2', alias = 'tst987', email = 'testgmail467@yahoo.com',
         username = 'testuserggggggggg123@yahoo.com.dev',profileid = p.Id, timezonesidkey = 'America/Chicago', 
         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true);                
         insert u2;
         
		 Account objAcc = new Account();
         objAcc.name = 'Test';
         objAcc.Update_date__c = system.today();
         insert objAcc;
         
         Contact objCon = new Contact();
         objCon.AccountId = objAcc.Id;
         objCon.LastName = 'test';
         objCon.Email ='testgmail@yahoo.com';
         objCon.HasOptedOutOfEmail = true;
         
         Contact objCon1 = new Contact();
         objCon1.AccountId = objAcc.Id;
         objCon1.LastName = 'test';
         objCon1.Email ='testgmail123@yahoo.com';
         objCon1.HasOptedOutOfEmail = true;
         insert new List<Contact>{objCon, objCon1};
         
         System.runAs(u2)
         {
         	 Profile p1 = [SELECT id from profile WHERE name = 'Biocomposites COMMUNITY USER'];
         	 list<user> lstuser = new list<user>(); 
         	 User u = new User (lastname = 'testlast', alias = 'tst456', email = 'testgmail@yahoo.com',
	         username = 'testuserxkxjjxkxjjxjx@yahoo.com.dev', ProfileId = p1.Id, timezonesidkey = 'America/Chicago', 
	         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true, ContactId = objCon.Id);
	         User u1 = new User (lastname = 'testlast1', alias = 'tst567', email = 'testgmail123@yahoo.com',
	         username = 'testusereeeeeeeee123@yahoo.com.dev', ProfileId = p1.Id, timezonesidkey = 'America/Chicago', 
	         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = false, ContactId = objCon1.Id);                   
	         lstuser.add(u);
	         lstuser.add(u1);
	         insert lstuser;	         
         }
      
         Campaign objcam = new Campaign( Name = 'TestView');         
       	 insert objcam;
       	 
       	 CampaignMember campMem1 = new CampaignMember(CampaignId = objcam.Id, ContactId = objCon.Id, Status = 'Sent');
       	 CampaignMember campMem2 = new CampaignMember(CampaignId = objcam.Id, ContactId = objCon1.Id, Status = 'Sent');
       	 insert new List<CampaignMember>{campMem1, campMem2};
       	 
       	 Test.startTest();       	 
       	 	Database.executeBatch(new BatchToRemoveInactCampMem());
       	 Test.stopTest();
       	 
       	 List<CampaignMember> campaignMemRecords = [Select id, ContactId, CampaignId from CampaignMember];
       	 System.assertEquals(1, campaignMemRecords.size());     	 
	}  
	
	static testMethod void testBatch1() 
	{
		 Profile p = [SELECT id from profile WHERE name = 'System Administrator'];
		 
		 User u2 = new User (lastname = 'testlast2', alias = 'tst987', email = 'testgmail467@yahoo.com',
         username = 'testuserggggggggg123@yahoo.com.dev',profileid = p.Id, timezonesidkey = 'America/Chicago', 
         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true);                
         insert u2;
         
		 Account objAcc = new Account();
         objAcc.name = 'Test';
         objAcc.Update_date__c = system.today();
         insert objAcc;
         
         Contact objCon = new Contact();
         objCon.AccountId = objAcc.Id;
         objCon.LastName = 'test';
         objCon.Email ='testgmail@yahoo.com';
         objCon.HasOptedOutOfEmail = true;
         
         Contact objCon1 = new Contact();
         objCon1.AccountId = objAcc.Id;
         objCon1.LastName = 'test';
         objCon1.Email ='testgmail123@yahoo.com';
         objCon1.HasOptedOutOfEmail = true;
         insert new List<Contact>{objCon, objCon1};
         
         Profile p1 = [SELECT id from profile WHERE name = 'Biocomposites COMMUNITY USER'];
     	 list<user> lstuser = new list<user>(); 
     	 User u = new User (lastname = 'testlast', alias = 'tst456', email = 'testgmail@yahoo.com',
         username = 'testuserxkxjjxkxjjxjx@yahoo.com.dev', ProfileId = p1.Id, timezonesidkey = 'America/Chicago', 
         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true, ContactId = objCon.Id);
         User u1 = new User (lastname = 'testlast1', alias = 'tst567', email = 'testgmail123@yahoo.com',
         username = 'testusereeeeeeeee123@yahoo.com.dev', ProfileId = p1.Id, timezonesidkey = 'America/Chicago', 
         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true, ContactId = objCon1.Id);                   
         lstuser.add(u);
         lstuser.add(u1);
         
         System.runAs(u2)
         {
	         insert lstuser;	         
         }
      
         Campaign objcam = new Campaign( Name = 'TestView'); 
         Campaign objcam1 = new Campaign( Name = 'TestViewDifferent');         
       	 insert new List<Campaign>{objcam, objcam1};
       	 
       	 CampaignMember campMem1 = new CampaignMember(CampaignId = objcam.Id, ContactId = objCon.Id, Status = 'Sent');
       	 CampaignMember campMem2 = new CampaignMember(CampaignId = objcam.Id, ContactId = objCon1.Id, Status = 'Sent');
       	 insert new List<CampaignMember>{campMem1, campMem2};
       	 
       	 
       	 System.runAs(u2)
         {
         	u1.Community_View__c = 'TestViewDifferent';
         	update u1;
         }
       	 
       	 Test.startTest();       	 
       	 	Database.executeBatch(new BatchToRemoveInactCampMem());
       	 Test.stopTest();
       	 
       	 List<CampaignMember> campaignMemRecords = [Select id, ContactId, CampaignId from CampaignMember];
       	 System.assertEquals(2, campaignMemRecords.size());     	 
	}
	
	static testMethod void testBatchScheduler() 
	{
		 Profile p = [SELECT id from profile WHERE name = 'System Administrator'];
		 
		 User u2 = new User (lastname = 'testlast2', alias = 'tst987', email = 'testgmail467@yahoo.com',
         username = 'testuserggggggggg123@yahoo.com.dev',profileid = p.Id, timezonesidkey = 'America/Chicago', 
         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true);                
         insert u2;
         
		 Account objAcc = new Account();
         objAcc.name = 'Test';
         objAcc.Update_date__c = system.today();
         insert objAcc;
         
         Contact objCon = new Contact();
         objCon.AccountId = objAcc.Id;
         objCon.LastName = 'test';
         objCon.Email ='testgmail@yahoo.com';
         objCon.HasOptedOutOfEmail = true;
         
         Contact objCon1 = new Contact();
         objCon1.AccountId = objAcc.Id;
         objCon1.LastName = 'test';
         objCon1.Email ='testgmail123@yahoo.com';
         objCon1.HasOptedOutOfEmail = true;
         insert new List<Contact>{objCon, objCon1};
         
         System.runAs(u2)
         {
         	 Profile p1 = [SELECT id from profile WHERE name = 'Biocomposites COMMUNITY USER'];
         	 list<user> lstuser = new list<user>(); 
         	 User u = new User (lastname = 'testlast', alias = 'tst456', email = 'testgmail@yahoo.com',
	         username = 'testuserxkxjjxkxjjxjx@yahoo.com.dev', ProfileId = p1.Id, timezonesidkey = 'America/Chicago', 
	         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = true, ContactId = objCon.Id);
	         User u1 = new User (lastname = 'testlast1', alias = 'tst567', email = 'testgmail123@yahoo.com',
	         username = 'testusereeeeeeeee123@yahoo.com.dev', ProfileId = p1.Id, timezonesidkey = 'America/Chicago', 
	         localesidkey = 'en_US', emailencodingkey = 'UTF-8', languagelocalekey = 'en_US',Community_View__c = 'TestView', IsActive = false, ContactId = objCon1.Id);                   
	         lstuser.add(u);
	         lstuser.add(u1);
	         insert lstuser;	         
         }
      
         Campaign objcam = new Campaign( Name = 'TestView');         
       	 insert objcam;
       	 
       	 CampaignMember campMem1 = new CampaignMember(CampaignId = objcam.Id, ContactId = objCon.Id, Status = 'Sent');
       	 CampaignMember campMem2 = new CampaignMember(CampaignId = objcam.Id, ContactId = objCon1.Id, Status = 'Sent');
       	 insert new List<CampaignMember>{campMem1, campMem2};
       	 
       	 Test.startTest();       	 
       	 	BatchToRemoveInactCampMemScheduler.batchScheduler();
       	 Test.stopTest(); 	 
	}
}