unpackaged/main/default/objects/Account/fields/Update_date__c.field-meta.xml
<CustomField>
    <fullName>Update_date__c</fullName>
    <label>Update date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Show_In_Hub_Push__c.field-meta.xml
<CustomField>
    <fullName>Show_In_Hub_Push__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show In Hub Push</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Standard_User_Profile__c.field-meta.xml
<CustomField>
    <fullName>Standard_User_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Standard User Profile</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/Community_Items__c.object-meta.xml
<CustomObject>
    <label>Community Item</label>
    <nameField>
        <displayFormat>ComID-{00}</displayFormat>
        <label>Community Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Items__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>Customer Community Login User cloned</fullName>
            </value>
            <value>
                <fullName>Distributors - EU (English)</fullName>
            </value>
            <value>
                <fullName>Distributors - India</fullName>
            </value>
            <value>
                <fullName>Distributors - USA</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Market Development – UK</fullName>
            </value>
            <value>
                <fullName>Regional Managers – USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing collateral</fullName>
            </value>
            <value>
                <fullName>Sales tools</fullName>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Contact us</fullName>
            </value>
            <value>
                <fullName>Internal only</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Topic of Interest / Notices</fullName>
            </value>
            <value>
                <fullName>Tutorial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Brainshark Training</fullName>
            </value>
            <value>
                <fullName>Video box</fullName>
            </value>
            <value>
                <fullName>Publication Library</fullName>
            </value>
            <value>
                <fullName>Featured Video</fullName>
            </value>
            <value>
                <fullName>Featured Item</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Continuing Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/URL_For_Image__c.field-meta.xml
<CustomField>
    <fullName>URL_For_Image__c</fullName>
    <label>URL For Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ComunityItemTypeTemplate__c/ComunityItemTypeTemplate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Community Item Email Template Map</label>
</CustomObject>

unpackaged/main/default/objects/ComunityItemTypeTemplate__c/fields/CommunityItemRecordType__c.field-meta.xml
<CustomField>
    <fullName>CommunityItemRecordType__c</fullName>
    <label>Community Item RecordType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ComunityItemTypeTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Email Template Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/CustomProfilePermissions__c/CustomProfilePermissions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Hub Email Button Permissions</label>
</CustomObject>

unpackaged/main/default/classes/Test_UserCommunityViewValCon.cls
@isTest
private class Test_UserCommunityViewValCon {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
   
       
        
           string strName;
           string strType;
           
            Account objA1 = new Account();
            objA1.Name = 'testAcc';
            objA1.Update_date__c = system.today();
            insert objA1;
            
            Contact objC1 = new Contact();
            objC1.LastName = 'testCom';
            objC1.Accountid = objA1.id;
            objC1.Email = 'test@gmail.com';
            insert objC1;        
            
            Contact objC22 = new Contact();
            objC22.LastName = 'testCom';
            objC22.Accountid = objA1.id;
            objC22.Email = 'test@gmail.com';
            insert objC22;        
                 
            Campaign objCmp1 = new Campaign();
            objCmp1.Name = 'testCampName';
            objCmp1.Show_In_Hub_Push__c = true;
            objCmp1.IsActive = true;
            objCmp1.Standard_User_Profile__c = true;
            insert objCmp1;
            
            Campaign objCmp2 = new Campaign();
            objCmp2.Name = 'testCampName2';
            objCmp2.Show_In_Hub_Push__c = true;
            objCmp2.IsActive = true;
            objCmp2.Standard_User_Profile__c = true;
            insert objCmp2;
            
            
            /*list<CampaignMember> lstMem = new list<CampaignMember>();
            CampaignMember objMem2 = new CampaignMember();
            objMem2.CampaignId = objCmp1.id;
            objMem2.ContactId = objC1.id;
            insert objMem2;*/
            
            /*CampaignMember objMem3 = new CampaignMember();
            objMem3.CampaignId = objCmp1.id;
            objMem3.ContactId = objC22.id;
            insert objMem3;*/
            
            
            //lstMem.add(objMem2);
            //lstMem.add(objMem3);
            
            
            list<CampaignMember> lstCampmem = new list<CampaignMember>();
            CampaignMember objMem4 = new CampaignMember();
            objMem4.CampaignId = objCmp2.id;
            objMem4.ContactId = objC22.id;
            insert objMem4;
            lstCampmem.add(objMem4);
            
            
       
        list<Recordtype > lstRec = [SELECT ID,Name, SobjectType from Recordtype WHERE SobjectType='Community_Items__c' ];
           Community_Items__c objCus = new Community_Items__c();
           objCus.Type__c  ='Marketing collateral';
           objCus.Title__c = 'testitle';
           objCus.URL_For_Image__c =  'testIMG';
           objCus.Profile__c = 'Management';
           if(lstRec[0].id != null){
                  objCus.RecordTypeId = lstRec[0].id;
           }
           insert objCus;
           
           strName = objCus.id;
           strType = objCus.Title__c;
           ApexPages.StandardController sc = new ApexPages.standardController(objCus);
           UserCommunityViewValCon objCon = new UserCommunityViewValCon(sc);
           ApexPages.currentPage().getParameters().put('id',objCus.id);
           objCon.getItems();
           //string strFName = objCmp1.Name+' '+'(' + lstMem.size() +')';
           string strSName = objCmp2.Name+' '+'('+lstCampmem.size() +')';
           objCon.leftselected = new list<String>{strSName};
           objCon.rightselected = new list<String>{strSName};
           objCon.rightvalues = new Set<String>{strSName};
           objCon.selectedValues();
           objCon.getSelectedValues();
           objCon.unselectclick();
           objCon.getUnSelectedValues();
          
          
          
           User thisUser4 = [ Select Id from User where Id = :UserInfo.getUserId() ];
           System.runAs(thisUser4){
           ComunityItemTypeTemplate__c  mycs2 = ComunityItemTypeTemplate__c.getValues('Test');
           if(mycs2 == null) {
           mycs2 = new ComunityItemTypeTemplate__c();
           mycs2.Name = '1';
           mycs2.CommunityItemRecordType__c = 'Test';
           mycs2.Template_Name__c = 'testTemp';
           insert mycs2;
           }
           }
           
            objCon.Preparedata();
            objCon.SendMail();
            
            Account objA = new Account();
            objA.Name = 'testAcc';
            objA.Update_date__c = system.today();
            insert objA;
            
            Contact objC = new Contact();
            objC.LastName = 'testCom';
            objC.Accountid = objA.id;
            objC.Email = 'test@gmail.com';
            insert objc;        
            
             Contact objC2 = new Contact();
            objC2.LastName = 'testCom';
            objC2.Accountid = objA.id;
            objC2.Email = 'test@gmail.com';
            insert objc2;        
            
                 
            Campaign objCmp = new Campaign();
            objCmp.Name = 'testCampName';
            insert objCmp;
            
             Campaign objCmp22 = new Campaign();
            objCmp22.Name = 'testCampName2';
            insert objCmp22;
            
            /*CampaignMember objMem = new CampaignMember();
            objMem.CampaignId = objCmp.id;
            objMem.ContactId = objc.id;
            insert objMem;*/
            
            /*CampaignMember objMem1 = new CampaignMember();
            objMem1.CampaignId = objCmp.id;
            objMem1.ContactId = objc2.id;
            insert objMem1;*/
            
            
      
    }
    
    static testMethod void myUnitTest2(){
       
            Community_Items__c objCus = new Community_Items__c();
            objCus.Type__c  ='Marketing collateral';
            objCus.Title__c = 'testitle';
            objCus.URL_For_Image__c =  'testIMG';
            objCus.Profile__c = 'Management';
           
            insert objCus;
            User thisUser = [ Select Id from User where Id = :UserInfo.getUserId() ];
            System.runAs( thisUser ){
            CustomProfilePermissions__c  mycs = CustomProfilePermissions__c.getValues('System Administrator');
            if(mycs == null) {
            mycs = new CustomProfilePermissions__c(Name= 'System Administrator');
            insert mycs;
            }
            }    
            EmailToComunityTypeCon.SendNotification(objCus.id);
            Community_Items__c objCus1 = new Community_Items__c();
            objCus1.Title__c = 'testitle';
            objCus1.URL_For_Image__c =  'testIMG';
            objCus1.Profile__c = 'Management';
            insert objCus1;
            User thisUser1 = [ Select Id from User where Id = :UserInfo.getUserId() ];
            System.runAs( thisUser1 ){
            CustomProfilePermissions__c  mycs1 = CustomProfilePermissions__c.getValues('System Administrator');
            if(mycs1 == null) {
            mycs1 = new CustomProfilePermissions__c(Name= 'System Administrator');
            insert mycs1 ;
            }
            }
        
            EmailToComunityTypeCon.SendNotification(objCus1.id);
            Community_Items__c objCus2 = new Community_Items__c();
            objCus2.Title__c = 'testitle';
            objCus2.Type__c = 'test';
            objCus2.URL_For_Image__c =  'testIMG';
            objCus2.Profile__c = 'Management';
            insert objCus2;
             User thisUser2 = [ Select Id from User where Id = :UserInfo.getUserId() ];
            System.runAs( thisUser1 ){
            ComunityItemTypeTemplate__c  mycs2 = ComunityItemTypeTemplate__c.getValues('Test');

            if(mycs2 == null) {
            mycs2 = new ComunityItemTypeTemplate__c();
            mycs2.Name = '1';
            mycs2.CommunityItemRecordType__c = 'test';
            mycs2.Template_Name__c = 'testTemp';
            insert mycs2;
            }
            }
            EmailToComunityTypeCon.SendNotification(objCus2.id);
      
    }
     
}