unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Hospital_in_a_Distributor__c/Hospital_in_a_Distributor__c.object-meta.xml
<CustomObject>
    <label>Hospital in a Distributor</label>
    <nameField>
        <displayFormat>DH{0000}</displayFormat>
        <label>Hospital in a Distributor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hospitals in Distributors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hospital_in_a_Distributor__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hospitals</relationshipLabel>
    <relationshipName>Hospitals_in_Distributors1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Hospital_in_a_Distributor__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor</relationshipLabel>
    <relationshipName>Hospitals_in_Distributors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/Surgeon_in_Hospital__c.object-meta.xml
<CustomObject>
    <label>Surgeon in Hospital</label>
    <nameField>
        <displayFormat>SH {0000}</displayFormat>
        <label>Surgeon in Hospital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surgeons in Hospital</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeons in Hospital (Distributor)</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeons</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

unpackaged/main/default/classes/SurgeonInHospitalRestriction.cls
/**
* @description Class used to restrict data returned to app via mc utils syncMobileTable.
*              Restricts object Surgeon_in_Hospital__c records for a user.
*
*   To implement in Salesforce:
*     - Create a MobileCaddy 'Support Component' record with field mobilecaddy1__Name__c = SurgeonInHospitalRestriction
*     - On the MobileCaddy 'Mobile Table' record, set field 'Platform Object Support' to record created above
**/
global without sharing class SurgeonInHospitalRestriction implements mobilecaddy1.RestrictionInterface001_mc {

  global Set<Id> returnRestrictedIds(String jsonParams) {

    // Get running user record
    User user = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];

    // Run different code if NOT community user (runs with sharing)
    if (user.ContactId == null) return SurgeonInHospitalNonCommunity.returnRestrictedIds();

    // Community users - gets data without sharing
    //============================================

    // Get limit from label
    String surgeonInHospitalCommunityUserLimitLabel = Label.SurgeonInHospitalCommunityUserLimit;
    Integer surgeonInHospitalCommunityUserLimit = isInteger(surgeonInHospitalCommunityUserLimitLabel) ? Integer.ValueOf(surgeonInHospitalCommunityUserLimitLabel) : 2500;

    // List of surgeons/hospitals we'll return Ids for
    List<Surgeon_in_Hospital__c> queryResults = new List<Surgeon_in_Hospital__c>();
    // Distributor Id used to restrict hospitals, which are then used to restrict surgeon/hospitals
    Set<Id> distributorId = new Set<Id>();

    // Community user will have an associated Contact record. Get the contact's distributor id from this record
    List<Contact> contact = [SELECT AccountId FROM Contact WHERE Id = :user.ContactId LIMIT 1];
    if (contact.size() > 0) {
      if (contact[0].AccountId != null) {
        distributorId.add(contact[0].AccountId);
      }
    }

  	// Use distributor id to select surgeons/hospitals
  	if (distributorId.size() > 0) {
  		queryResults = [SELECT Id
  						FROM Surgeon_in_Hospital__c
  						WHERE Hospital__c IN (SELECT Hospital__c FROM Hospital_in_a_Distributor__c WHERE Distributor__c IN :distributorId)];
  	} // end distributors found check if

    // Raise an error if more records are to be returned than our limit
    if (queryResults.size() > surgeonInHospitalCommunityUserLimit) {
      throw new mobilecaddy1.MC_001_mcException(mobilecaddy1.MC_001_mcException.MC_EXT_CLASS_LIMITS,'SurgeonInHospitalRestriction class - more than ' + surgeonInHospitalCommunityUserLimit + ' Surgeon_in_Hospital__c records will be returned.');
    }

    // Return set of ids
    if (queryResults.isEmpty()) {
      return new Set<Id>();
    } else {
      return (new Map<Id,SObject>(queryResults)).keySet();
    }
  } // end

  private static Boolean isInteger(String test) {
    try {
      Integer x = Integer.valueOf(test);
      return true;
    } catch(Exception e) {
      return false;
    }
  }

} // end class