unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/DOF__c/DOF__c.object-meta.xml
<CustomObject>
    <description>Used for recorrding orders added by the Hub Mobile App</description>
    <label>DOF</label>
    <nameField>
        <displayFormat>DOF-{000000}</displayFormat>
        <label>DOF Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DOF__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Hospital the Surgeon requires the product for.</inlineHelpText>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DOFs (Hospital)</relationshipLabel>
    <relationshipName>DOFs1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Hospital_Text_Id__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Text_Id__c</fullName>
    <description>Used only by code to temporarily hold the Hospital Id</description>
    <inlineHelpText>Used only by code to temporarily hold the Hospital Id</inlineHelpText>
    <label>Hospital Text Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Send_Process_Has_Completed__c.field-meta.xml
<CustomField>
    <fullName>Send_Process_Has_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Process Has Completed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Signature_Capture__c.field-meta.xml
<CustomField>
    <fullName>Signature_Capture__c</fullName>
    <inlineHelpText>Used to store the encoded signature as recorded on the mobile app.</inlineHelpText>
    <label>Signature Capture</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Signature_Capture_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Signature_Capture_Document_Id__c</fullName>
    <description>Id of the document record that holds the signature which is then used to display the signature in visualforce email template</description>
    <label>Signature Capture Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Surgeon that requested the Order</inlineHelpText>
    <label>Surgeon</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>DOFs</relationshipLabel>
    <relationshipName>DOFs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/fields/Surgeon_Text_Id__c.field-meta.xml
<CustomField>
    <fullName>Surgeon_Text_Id__c</fullName>
    <description>Used by code to temporarily hold the Surgeon Id.</description>
    <inlineHelpText>Used by code to temporarily hold the Surgeon Id.</inlineHelpText>
    <label>Surgeon Text Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DOF__c/recordTypes/DOF.recordType-meta.xml
<RecordType>
    <fullName>DOF</fullName>
    <active>true</active>
    <label>DOF</label>
</RecordType>

unpackaged/main/default/classes/DOF_TriggerHandler.cls
public class DOF_TriggerHandler {

    private boolean isExecuting = false;
    private integer batchSize = 0;
    
    // Constructor
    public DOF_TriggerHandler(boolean isExecuting, integer size){
        this.isExecuting = isExecuting;
        this.batchSize = size;
    } // end constructor
    
    // Because the Community Users cannot write to the Account or Contact lookups (rubbish permissions)
    // we move them to sister fields on the before insert and then move and update on the after insert
    public void onBeforeInsert(DOF__c[] insertedRecords){
    	if ((UserInfo.getUserType() == 'CspLitePortal') || Test.isRunningTest()) {
	    	for (DOF__c dof : insertedRecords) {
	    		dof.Hospital_Text_Id__c = dof.Hospital__c;
	    		dof.Hospital__c = null;
	    		dof.Surgeon_Text_Id__c = dof.Surgeon__c;
	    		dof.Surgeon__c = null;
	    	} // end loop through inserted records for
    	} // end community user check if
    } // end onBeforeInsert
    
    public void onAfterInsert(DOF__c[] insertedRecords){
        Set<Id> dofIdsList = new Set<Id>();
    	if ((UserInfo.getUserType() == 'CspLitePortal') || Test.isRunningTest()) {
	    	List<DOF__c> updatedDOFs = new List<DOF__c>();
	    	for (DOF__c dof : insertedRecords) {
	    		if ((dof.Hospital_Text_Id__c != null) || (dof.Surgeon_Text_Id__c != null)) {
	    			DOF__c updateDOF = new DOF__c(Id = dof.Id);
	    			updatedDOFs.add(updateDOF);
	    			updateDOF.Hospital__c = dof.Hospital_Text_Id__c;
	    			updateDOF.Hospital_Text_Id__c = null;
	    			updateDOF.Surgeon__c = dof.Surgeon_Text_Id__c;
	    			updateDOF.Surgeon_Text_Id__c = null;
	    		} // end check needs shifting if
	    	} // end loop through DOFs for
	    	
	    	// Update changed recs
	    	if (!updatedDOFs.isEmpty()) {
	    		update updatedDOFs;
	    	} // end check recs updated if

            // Loop through Dof
            for(DOF__c dof : insertedRecords){
                if(dof.Send_Process_Has_Completed__c){
                    dofIdsList.add(dof.Id);
                }
            }

            // if dof ids list is not empty
            if(!dofIdsList.isEmpty()){
                SendDOFEmailController.sendEmail(dofIdsList);
            }

    	} // end community user check if

        // create document records for signature
        List<Dof__c> dofList = [SELECT Id, Name, Signature_Capture_Document_Id__c, Signature_Capture__c FROM Dof__c WHERE Id IN: new Map<Id,Dof__c>(insertedRecords).keySet() LIMIT 500];
        DOFHelper.upsertSignatureInDocuments(dofList,null,true);
    } // end onBeforeInsert

    public void onBeforeUpdate(List<DOF__c> updatedRecords,Map<Id, DOF__c> oldUpdatedRecordsMap){
    	// capture signature in documents
    	DOFHelper.upsertSignatureInDocuments(updatedRecords,oldUpdatedRecordsMap,false);
        DOFHelper.updateDistributors(updatedRecords);
    } // end onBeforeInsert

    public void onBeforeDelete(List<DOF__c> deletedRecords){
    	// delete documents
    	DOFHelper.deleteDocuments(deletedRecords);

    } // end onBeforeInsert

    public void onAfterUpate(List<DOF__c> newRecords, Map<Id,Dof__c> oldRecordsMap){
        Set<Id> dofIdsList = new Set<Id>();

        // Loop through Dof
        for(DOF__c dof : newRecords){
            if(dof.Send_Process_Has_Completed__c && oldRecordsMap.containsKey(dof.Id) && !oldRecordsMap.get(dof.Id).Send_Process_Has_Completed__c){
                dofIdsList.add(dof.Id);
            }
        }

        // if dof ids list is not empty
        if(!dofIdsList.isEmpty()){
            SendDOFEmailController.sendEmail(dofIdsList);
        }
       
    }
} // end trigger handler