unpackaged/main/default/objects/Community_Item_Permission_Link__c/Community_Item_Permission_Link__c.object-meta.xml
<CustomObject>
    <label>Community Item Permission / Link</label>
    <nameField>
        <displayFormat>Perm-{00}</displayFormat>
        <label>Community Item Permission / Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Item Permissions / Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipLabel>Community Item Permissions / Links</relationshipLabel>
    <relationshipName>Community_Item_Permissions_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/Community_Items__c.object-meta.xml
<CustomObject>
    <label>Community Item</label>
    <nameField>
        <displayFormat>ComID-{00}</displayFormat>
        <label>Community Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Items__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>Customer Community Login User cloned</fullName>
            </value>
            <value>
                <fullName>Distributors - EU (English)</fullName>
            </value>
            <value>
                <fullName>Distributors - India</fullName>
            </value>
            <value>
                <fullName>Distributors - USA</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Market Development – UK</fullName>
            </value>
            <value>
                <fullName>Regional Managers – USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <label>App Item</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Content Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Content_Item__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipName>Content_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ContentItemRestrictionV2i3Test.cls
@isTest
private class ContentItemRestrictionV2i3Test {
    private static User u;

    private static void initData() {
        // Get profile and create user record
        String profileName = 'System Administrator';
        Profile p = [SELECT Id FROM Profile WHERE Name = :profileName];
        System.assertNotEquals(null, p.Id, profileName + ' profile not found');

        // Create user
        u = new User(Alias='aucalias', Email='test@testorg.com',
          EmailEncodingKey='UTF-8', LastName='Tester', LanguageLocaleKey='en_US',
          LocaleSidKey='en_US', ProfileId=p.Id,
          TimeZoneSidKey='America/Los_Angeles', UserName='testAdmin@testorg1234.com');

        u.Community_View__c = 'System Administrator';
        insert u;
        System.assertNotEquals(null, u.Id, 'User not created');

        // Create Community_Items__c
        Community_Items__c communityItem = new Community_Items__c();
        insert communityItem;
        System.assertNotEquals(null, communityItem.Id, 'Community Item not created');

        // Community_Item_Permission_Link__c
        Community_Item_Permission_Link__c link = new Community_Item_Permission_Link__c();
        link.Community_Item__c = communityItem.Id;
        link.Profile__c = 'System Administrator';
        insert link;
        System.assertNotEquals(null, link.Id, 'Community_Item_Permission_Link__c not created');

        // Create Content Item
        Content_Item__c ci = new Content_Item__c();
        ci.Status__c = 'Active';
        ci.Available_in_Version__c = 'V001;V002';
        ci.Community_Item__c = communityItem.Id;
        insert ci;
        System.assertNotEquals(null, ci.Id, 'Content Item not created');
    } // end initData

    public static testMethod void test_returnRestrictedIds() {
        initData();

        mobilecaddy1__Mobile_Table__c mobileTableRec = new mobilecaddy1__Mobile_Table__c(
            mobilecaddy1__Mobile_Table_Version__c = '001',
            mobilecaddy1__Mobile_Table_Status__c = 'Inactive',
            mobilecaddy1__Dev_Status__c = 'Developing',
            mobilecaddy1__Sync_Priority__c = 1,
            mobilecaddy1__Build_Order__c = 1,
            mobilecaddy1__Refresh_Record_Limit__c = 1000,
            mobilecaddy1__Refresh_Record_Limit_Install__c = 1000
            );

        // Prepare map of input parameters to interace 2
        Map<String,Object> int2ParamMap = new Map<String,Object>();

        // Provide entire mobile table record to external class
        int2ParamMap.put('mobileTableRec',mobileTableRec);

        // Mark as a new install
        int2ParamMap.put('isInstall',true);

        // Provide set of ids already processed so that external class may ignore them on a more batch query
        int2ParamMap.put('idsAlreadyProcessed',null);

        // Ids on device
        int2ParamMap.put('idsOnDevice',null);

        // Refresh datetime
        int2ParamMap.put('refreshDatetime',0);

        // Serialise the map into JSON as a parameter
        String param = JSON.serialize(int2ParamMap);

        System.runAs(u) {
            // Make the call and get the response
            ContentItemRestrictionV2i3 restInst = new ContentItemRestrictionV2i3();
            String supportResponse = restInst.returnRestrictedIds(param);

            // Deserialise the response
            Map<String,Object> responseMap = (Map<String,Object>)JSON.deserializeUntyped(supportResponse);

            // Get list of ids from response
            List<Object> idsMap = (List<Object>)responseMap.get('ids');

            System.assertEquals(1,idsMap.size(),'Ids not returned');
        }
    } // end testMethod

    public static testMethod void test_idsStillValid() {
        initData();

        mobilecaddy1__Mobile_Table__c mobileTableRec = new mobilecaddy1__Mobile_Table__c(
            mobilecaddy1__Mobile_Table_Version__c = '001',
            mobilecaddy1__Mobile_Table_Status__c = 'Inactive',
            mobilecaddy1__Dev_Status__c = 'Developing',
            mobilecaddy1__Sync_Priority__c = 1,
            mobilecaddy1__Build_Order__c = 1,
            mobilecaddy1__Refresh_Record_Limit__c = 1000,
            mobilecaddy1__Refresh_Record_Limit_Install__c = 1000
            );

        // Prepare map of input parameters to interace 2
        Map<String,Object> int2ParamMap = new Map<String,Object>();

        // Provide entire mobile table record to external class
        int2ParamMap.put('mobileTableRec',mobileTableRec);

        // Add an id to device
        List<Content_Item__c> contentItem = [SELECT Id FROM Content_Item__c];
        int2ParamMap.put('idsOnDevice',new List<Object>{contentItem[0].Id});

        // Serialise the map into JSON as a parameter
        String param = JSON.serialize(int2ParamMap);

        System.runAs(u) {
            // Make the call and get the response
            ContentItemRestrictionV2i3 restInst = new ContentItemRestrictionV2i3();
            String supportResponse = restInst.idsStillValid(param);

            // Deserialise the response
            Map<String,Object> responseMap = (Map<String,Object>)JSON.deserializeUntyped(supportResponse);

            // Get list of ids from response
            List<Object> idsMap = (List<Object>)responseMap.get('stillValidIds');

            System.assertEquals(1,idsMap.size(),'Id not returned');
        }
    } // end testMethod

} // end class