unpackaged/main/default/objects/Community_Item_Permission_Link__c/Community_Item_Permission_Link__c.object-meta.xml
<CustomObject>
    <label>Community Item Permission / Link</label>
    <nameField>
        <displayFormat>Perm-{00}</displayFormat>
        <label>Community Item Permission / Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Item Permissions / Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Button_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Button_Link_URL__c</fullName>
    <label>Button / Link URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipLabel>Community Item Permissions / Links</relationshipLabel>
    <relationshipName>Community_Item_Permissions_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/Community_Items__c.object-meta.xml
<CustomObject>
    <label>Community Item</label>
    <nameField>
        <displayFormat>ComID-{00}</displayFormat>
        <label>Community Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Items__c/fields/ALT_Tag__c.field-meta.xml
<CustomField>
    <fullName>ALT_Tag__c</fullName>
    <label>ALT Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>Customer Community Login User cloned</fullName>
            </value>
            <value>
                <fullName>Distributors - EU (English)</fullName>
            </value>
            <value>
                <fullName>Distributors - India</fullName>
            </value>
            <value>
                <fullName>Distributors - USA</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Market Development – UK</fullName>
            </value>
            <value>
                <fullName>Regional Managers – USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Sort_Number__c.field-meta.xml
<CustomField>
    <fullName>Sort_Number__c</fullName>
    <label>Sort Number</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing collateral</fullName>
            </value>
            <value>
                <fullName>Sales tools</fullName>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Contact us</fullName>
            </value>
            <value>
                <fullName>Internal only</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Topic of Interest / Notices</fullName>
            </value>
            <value>
                <fullName>Tutorial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Brainshark Training</fullName>
            </value>
            <value>
                <fullName>Video box</fullName>
            </value>
            <value>
                <fullName>Publication Library</fullName>
            </value>
            <value>
                <fullName>Featured Video</fullName>
            </value>
            <value>
                <fullName>Featured Item</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Continuing Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/URL_For_Image__c.field-meta.xml
<CustomField>
    <fullName>URL_For_Image__c</fullName>
    <label>URL For Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/recordTypes/Logo.recordType-meta.xml
<RecordType>
    <fullName>Logo</fullName>
    <active>true</active>
    <label>Logo</label>
</RecordType>

unpackaged/main/default/classes/Test_BioComCommunityclasses.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData = true)
private class Test_BioComCommunityclasses {

    static testMethod void myUnitTest() {
        
        List<RecordType> recs =[select id,Name from RecordType where SobjectType='Community_Items__c' and name='Topics Of Interest'];
        
        Community_Items__c  com = new Community_Items__c();
            com.ALT_Tag__c = 'Test';
            com.Content__c ='test content';
            com.Profile__c ='system administrator';
            com.Title__c ='test title';
            com.Type__c = 'Topic of Interest / Notices';
            com.URL_For_Image__c ='www.google.com';
            com.RecordTypeId = recs[0].id;
        insert com;
        
        Community_Item_Permission_Link__c link = new Community_Item_Permission_Link__c();
        link.Profile__c = 'system administrator';
        link.Button_Link_URL__c ='www.google.com';
        link.Community_Item__c = com.id;
        insert link;
        
        List<RecordType> recs1 =[select id,Name from RecordType where SobjectType='Community_Items__c' and name='Left Panel'];
        
        Community_Items__c  com1 = new Community_Items__c();
            com1.ALT_Tag__c = 'Test';
            com1.Content__c ='test content';
            com1.Profile__c ='system administrator';
            com1.Title__c ='test title';
            com1.Type__c = 'Topic of Interest / Notices';
            com1.URL_For_Image__c ='www.google.com';
            com1.RecordTypeId = recs1[0].id;
            com1.Sort_Number__c = 1;
        insert com1;
        
        Community_Item_Permission_Link__c link1 = new Community_Item_Permission_Link__c();
        link1.Profile__c = 'system administrator';
        link1.Button_Link_URL__c ='www.google.com';
        link1.Community_Item__c = com1.id;
        insert link1;
        
        List<RecordType> recs11 =[select id,Name from RecordType where SobjectType='Community_Items__c' and name='Logo'];
        
        Community_Items__c  com11 = new Community_Items__c();
            com11.ALT_Tag__c = 'Test';
            com11.Content__c ='test content';
            com11.Profile__c ='system administrator';
            com11.Title__c ='test title';
            com11.Type__c = 'Topic of Interest / Notices';
            com11.URL_For_Image__c ='www.google.com';
            com11.RecordTypeId = recs11[0].id;
            com11.Sort_Number__c = 2;
        insert com11;
        
         Community_Item_Permission_Link__c link11 = new Community_Item_Permission_Link__c();
        link11.Profile__c = 'system administrator';
        link11.Button_Link_URL__c ='www.google.com'; 
        link11.Community_Item__c = com11.id;
        insert link11;
        
        List<RecordType> recs111 =[select id,Name from RecordType where SobjectType='Community_Items__c' and name='Header Image'];
        
        Community_Items__c  com111 = new Community_Items__c();
            com111.ALT_Tag__c = 'Test';
            com111.Content__c ='test content';
            com111.Profile__c ='system administrator';
            com111.Title__c ='test title';
            com111.Type__c = 'Topic of Interest / Notices';
            com111.URL_For_Image__c ='www.google.com';
            com111.RecordTypeId = recs111[0].id;
            com111.Sort_Number__c = 3;
        insert com111;
        
         Community_Item_Permission_Link__c link111 = new Community_Item_Permission_Link__c();
        link111.Profile__c = 'system administrator';
        link111.Button_Link_URL__c ='www.google.com';
        link111.Community_Item__c = com111.id;
        insert link111;
        
        BiocompController obj = new BiocompController();
        obj.CommBannerLogoURL ='www.google.com';
        obj.CommLogoURL ='www.google.com';
        //obj.getlistMember();
        obj.getlistleftPanels();
        obj.ViewData();
        obj.indexAssigned = com111.id;
        obj.EmailSubject = 'test';
        obj.EmailText = 'test';
        obj.SendMessage();
        obj.leftPanelRecordId =com111.id;
        obj.elernid = com111.id; 
        obj.createLeftRecord();
        obj.createlinkRecord();
        obj.createElearnRecord();
        obj.TotalSize = 1;
        obj.nextBtnClick();
        obj.getPreviousButtonEnabled();
        obj.previousBtnClick();
        obj.getNextButtonDisabled();
        obj.selectedPage = '1';
        obj.getlistleftPanelsRes();
        obj.getlistleftPanelsInternalOnly();
        obj.showPopup();
        obj.closePopup();
        obj.svaeUserDetails();
        obj.getMapleftPanelsVideos();
        
        LoginPageForCommunityCon con = new LoginPageForCommunityCon();
        con.login();
        con.loginError();
        
        con.username ='chandu3@ceterna.com';
        con.password ='appshark@2014';
        con.username1 ='chandu3@ceterna.com';
        con.password1 ='appshark@2014';
        con.usernameToSendEmail ='chandu3@ceterna.com';
        con.login();
        con.loginError();
        con.sendEmailToUser();
        
    }
}