unpackaged/main/default/objects/Community_Item_Permission_Link__c/Community_Item_Permission_Link__c.object-meta.xml
<CustomObject>
    <label>Community Item Permission / Link</label>
    <nameField>
        <displayFormat>Perm-{00}</displayFormat>
        <label>Community Item Permission / Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Item Permissions / Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Button_Link_Text__c.field-meta.xml
<CustomField>
    <fullName>Button_Link_Text__c</fullName>
    <label>Button / Link Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Button_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Button_Link_URL__c</fullName>
    <label>Button / Link URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipLabel>Community Item Permissions / Links</relationshipLabel>
    <relationshipName>Community_Item_Permissions_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/Community_Items__c.object-meta.xml
<CustomObject>
    <label>Community Item</label>
    <nameField>
        <displayFormat>ComID-{00}</displayFormat>
        <label>Community Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Items__c/fields/ALT_Tag__c.field-meta.xml
<CustomField>
    <fullName>ALT_Tag__c</fullName>
    <label>ALT Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Brainshark_URL__c.field-meta.xml
<CustomField>
    <fullName>Brainshark_URL__c</fullName>
    <description>b=1&amp;</description>
    <formula>&quot;https://www.brainshark.com/biocomposites/vu?pi=&quot;&amp;Brainshark_9_Digit_Number__c
&amp;&quot;&amp;em=&quot;&amp; User_Name_No_Sp_Chars__c 
&amp;&quot;&amp;c1=&quot;&amp; $User.Id
&amp;&quot;&amp;c2=&quot;&amp; $User.ContactId
&amp;&quot;&amp;b=1&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brainshark URL</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>Customer Community Login User cloned</fullName>
            </value>
            <value>
                <fullName>Distributors - EU (English)</fullName>
            </value>
            <value>
                <fullName>Distributors - India</fullName>
            </value>
            <value>
                <fullName>Distributors - USA</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Market Development – UK</fullName>
            </value>
            <value>
                <fullName>Regional Managers – USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stimulan</fullName>
            </value>
            <value>
                <fullName>genex</fullName>
            </value>
            <value>
                <fullName>Internal Documents</fullName>
            </value>
            <value>
                <fullName>External Documents</fullName>
            </value>
            <value>
                <fullName>Subtype 5</fullName>
            </value>
            <value>
                <fullName>Subtype 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing collateral</fullName>
            </value>
            <value>
                <fullName>Sales tools</fullName>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Contact us</fullName>
            </value>
            <value>
                <fullName>Internal only</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Topic of Interest / Notices</fullName>
            </value>
            <value>
                <fullName>Tutorial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Brainshark Training</fullName>
            </value>
            <value>
                <fullName>Video box</fullName>
            </value>
            <value>
                <fullName>Publication Library</fullName>
            </value>
            <value>
                <fullName>Featured Video</fullName>
            </value>
            <value>
                <fullName>Featured Item</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Continuing Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Video_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_URL__c</fullName>
    <label>Video URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CommunitySearch.cls
public class CommunitySearch {
    
  @RemoteAction
  public static List<Community_Items__c> searchItems(String query) {
    // get current user
    String userId = UserInfo.getUserId();
    String userProfile = [SELECT Community_View__c FROM User WHERE Id = :userId].Community_View__c;
    // run search query
    query = '*' + query + '*';
    List<List<Community_Items__c>> items = [FIND :query IN ALL FIELDS RETURNING Community_Items__c (Id)];
    List<Community_Items__c> results = items[0];
    // get result ids
    Set<Id> resultIds = new Set<Id>();
    for (Integer i = 0; i < results.size(); i++) {
      resultIds.add(results[i].Id);
    }
    // query full item details checking user profile
    List<Community_Items__c> fullResults = [
      SELECT Id, Name, Description__c, Title__c, Type__c, Video_URL__c, RecordType.Name, 
        Brainshark_URL__c, Subtype__c, ALT_Tag__c,
        (SELECT Id, Button_Link_URL__c, Button_Link_Text__c 
         FROM Community_Item_Permissions_Links__r
         WHERE Profile__c = :userProfile
        )
      FROM Community_Items__c
      WHERE Id IN :resultIds
    ];
    return fullResults;
  }

}