unpackaged/main/default/objects/Community_Item_Permission_Link__c/Community_Item_Permission_Link__c.object-meta.xml
<CustomObject>
    <label>Community Item Permission / Link</label>
    <nameField>
        <displayFormat>Perm-{00}</displayFormat>
        <label>Community Item Permission / Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Item Permissions / Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipLabel>Community Item Permissions / Links</relationshipLabel>
    <relationshipName>Community_Item_Permissions_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <label>App Item</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Content Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Content_Item__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipName>Content_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Content_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/Mobile_Refresh__c.object-meta.xml
<CustomObject>
    <description>Used for Records that are mobilised and only need refreshing. Split by record type.</description>
    <label>Mobile Refresh</label>
    <nameField>
        <displayFormat>MRE-{000000}</displayFormat>
        <label>Mobile Refresh Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Refresh</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Available_in_Version__c.field-meta.xml
<CustomField>
    <fullName>Available_in_Version__c</fullName>
    <description>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced to only the Profile Menu Items that correspond to the Community Profile</description>
    <inlineHelpText>Sets whether the menu and sub menu items are processed for a specific version of the application. If a value is selected ie V001 then this menu or sub menu item will be returned in the initial query to return to the user - but this will be further reduced</inlineHelpText>
    <label>Available in Version</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V001</fullName>
            </value>
            <value>
                <fullName>V002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Dynamic_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_SOQL__c</fullName>
    <label>Dynamic SOQL</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Used for Name - can be applied differently for each Record Type</description>
    <inlineHelpText>Used for Name - can be applied differently for each Record Type</inlineHelpText>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Object_Reference__c.field-meta.xml
<CustomField>
    <fullName>Object_Reference__c</fullName>
    <label>Object Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobile_Refresh__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ContentItemRestriction.cls
/**
* @description Class used to restrict data returned to app via mc utils syncMobileTable.
*   To implement in Salesforce:
*     - Create a MobileCaddy 'Support Component' record with field mobilecaddy1__Name__c = ContentItemRestriction
*     - On the MobileCaddy 'Mobile Table' record, set field 'Platform Object Support' to record created above
**/
global class ContentItemRestriction implements mobilecaddy1.RestrictionInterface001_mc {

  global Set<Id> returnRestrictedIds(String jsonParams) {
    // Get community profile name from the user's User record
    User user = [SELECT Community_View__c, UserName FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];

    // Check to see if we have any dynamic soql used in testing,
    // to restrict amount of data for individual users (helps with memory size issues in Chrome codeflow testing)
    List<Mobile_Refresh__c> mr = [SELECT Dynamic_SOQL__c
                                  FROM Mobile_Refresh__c
                                  WHERE Name__c = :user.UserName
                                  AND Object_Reference__c = 'Content_Item__c'
                                  AND Status__c = 'Active' LIMIT 1];

    String testingDynamicSOQL = '';
    if (!mr.isEmpty()) {
      if (mr[0].Dynamic_SOQL__c != null && mr[0].Dynamic_SOQL__c != '') {
        testingDynamicSOQL = mr[0].Dynamic_SOQL__c;
      }
    }

    // Build the default soql to select records from Content_Item__c - based on the user's 'community profile' on User record
    String defaultDynamicSOQL = 'SELECT Id FROM Content_Item__c WHERE Community_Item__c IN ';
    defaultDynamicSOQL += '(SELECT Community_Item__c FROM Community_Item_Permission_Link__c WHERE Profile__c = \'' + user.Community_View__c + '\') ';
    defaultDynamicSOQL += 'AND Status__c = \'Active\'';
    defaultDynamicSOQL += 'AND Available_in_Version__c INCLUDES (\'V001\')';

    List<Content_Item__c> queryResults = new List<Content_Item__c>();
    if (testingDynamicSOQL != '') {
      // If we do have some dynamic soql from Mobile_Refresh__c then attempt to execute it.
      // Run the default soql if we have any exceptions
      try {
        queryResults = Database.query(testingDynamicSOQL);
      } catch (Exception e) {
        queryResults = Database.query(defaultDynamicSOQL);
      }
    } else {
      // Select records based on the user's community profile
      queryResults = Database.query(defaultDynamicSOQL);
    }

    // Return set of ids
    if (queryResults.isEmpty()) {
      return new Set<Id>();
    } else {
      return (new Map<Id,SObject>(queryResults)).keySet();
    }
  }

}