unpackaged/main/default/objects/Community_Item_Permission_Link__c/Community_Item_Permission_Link__c.object-meta.xml
<CustomObject>
    <label>Community Item Permission / Link</label>
    <nameField>
        <displayFormat>Perm-{00}</displayFormat>
        <label>Community Item Permission / Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Item Permissions / Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Button_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Button_Link_URL__c</fullName>
    <label>Button / Link URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Community_Item__c.field-meta.xml
<CustomField>
    <fullName>Community_Item__c</fullName>
    <label>Community Item</label>
    <referenceTo>Community_Items__c</referenceTo>
    <relationshipLabel>Community Item Permissions / Links</relationshipLabel>
    <relationshipName>Community_Item_Permissions_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Community_Item_Permission_Link__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/Community_Items__c.object-meta.xml
<CustomObject>
    <label>Community Item</label>
    <nameField>
        <displayFormat>ComID-{00}</displayFormat>
        <label>Community Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Items__c/fields/Abstract__c.field-meta.xml
<CustomField>
    <fullName>Abstract__c</fullName>
    <label>Abstract</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/ALT_Tag__c.field-meta.xml
<CustomField>
    <fullName>ALT_Tag__c</fullName>
    <label>ALT Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Marketing_Resources_URL__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Resources_URL__c</fullName>
    <label>Marketing Resources URL</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Our_View__c.field-meta.xml
<CustomField>
    <fullName>Our_View__c</fullName>
    <label>Key Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - Mid West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - North West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South Central</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South East</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - South West</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA - West Central</fullName>
            </value>
            <value>
                <fullName>Customer Community Login User cloned</fullName>
            </value>
            <value>
                <fullName>Distributors - EU (English)</fullName>
            </value>
            <value>
                <fullName>Distributors - India</fullName>
            </value>
            <value>
                <fullName>Distributors - USA</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Market Development – UK</fullName>
            </value>
            <value>
                <fullName>Regional Managers – USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Publishers__c.field-meta.xml
<CustomField>
    <fullName>Publishers__c</fullName>
    <label>Journal / Meeting</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Sort_Number__c.field-meta.xml
<CustomField>
    <fullName>Sort_Number__c</fullName>
    <label>Sort Number</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stimulan</fullName>
            </value>
            <value>
                <fullName>genex</fullName>
            </value>
            <value>
                <fullName>Internal Documents</fullName>
            </value>
            <value>
                <fullName>External Documents</fullName>
            </value>
            <value>
                <fullName>Subtype 5</fullName>
            </value>
            <value>
                <fullName>Subtype 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Text_For_Brainshark_Tile__c.field-meta.xml
<CustomField>
    <fullName>Text_For_Brainshark_Tile__c</fullName>
    <inlineHelpText>If you are entering info for the surgeon hub this is the text text in the tile</inlineHelpText>
    <label>Text For Brainshark Tile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing collateral</fullName>
            </value>
            <value>
                <fullName>Sales tools</fullName>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Contact us</fullName>
            </value>
            <value>
                <fullName>Internal only</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Topic of Interest / Notices</fullName>
            </value>
            <value>
                <fullName>Tutorial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Brainshark Training</fullName>
            </value>
            <value>
                <fullName>Video box</fullName>
            </value>
            <value>
                <fullName>Publication Library</fullName>
            </value>
            <value>
                <fullName>Featured Video</fullName>
            </value>
            <value>
                <fullName>Featured Item</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Continuing Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/URL_For_Image__c.field-meta.xml
<CustomField>
    <fullName>URL_For_Image__c</fullName>
    <label>URL For Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Video_Server_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_Server_URL__c</fullName>
    <label>Video Server URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Video_thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_thumbnail_URL__c</fullName>
    <label>Video thumbnail URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/fields/Video_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_URL__c</fullName>
    <label>Video URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Community_Items__c/recordTypes/Left_Panel.recordType-meta.xml
<RecordType>
    <fullName>Left_Panel</fullName>
    <active>true</active>
    <label>Left Panel</label>
</RecordType>

unpackaged/main/default/objects/Community_Items__c/recordTypes/Publication_Library.recordType-meta.xml
<RecordType>
    <fullName>Publication_Library</fullName>
    <active>true</active>
    <label>Publication Library</label>
</RecordType>

unpackaged/main/default/objects/Community_Items__c/recordTypes/Topics_Of_Interest.recordType-meta.xml
<RecordType>
    <fullName>Topics_Of_Interest</fullName>
    <active>true</active>
    <label>Topics Of Interest</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Community_View__c.field-meta.xml
<CustomField>
    <fullName>Community_View__c</fullName>
    <label>Community View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biocomposites - MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>Biocomposites - MARKET DEVELOPMENT MANAGER UK</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER CANADA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - REGIONAL MANAGER USA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER CHINA</fullName>
            </value>
            <value>
                <fullName>Biocomposites - SALES MANAGER INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR CANADA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR EU (English)</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR INDIA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>Community - DISTRIBUTOR USA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Surgeon</fullName>
            </value>
            <value>
                <fullName>Surgeon - Canada</fullName>
            </value>
            <value>
                <fullName>Surgeon - EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CommunityUtilities.cls
public class CommunityUtilities 
{
	public static Community_Items__c createTopicOfInterestCommunityItem(String title, String content)
	{
		Id recordTypeId = [Select Id from RecordType where SObjectType='Community_Items__c' and DeveloperName='Topics_Of_Interest'].Id;
		Community_Items__c toiRecord = new Community_Items__c(Type__c='Topic of Interest / Notices', 
        														RecordTypeId = recordTypeId,
        														Title__c =  title,
        														Content__c = content,
        														ALT_Tag__c = 'sample text',
        														Sort_Number__c = 1,
        														Text_For_Brainshark_Tile__c = 'brainshark text',
        														URL_For_Image__c = 'https://biocomposites.force.com/servlet/servlet.ImageServer?id=015U0000003Dual&oid=00DU0000000Levb',
        														Video_Server_URL__c = 'https://biocomposites.force.com/servlet/servlet.ImageServer?id=015U0000003Dual&oid=00DU0000000Levb',
        														Video_thumbnail_URL__c = 'https://biocomposites.force.com/servlet/servlet.ImageServer?id=015U0000003Dual&oid=00DU0000000Levb',
        														Video_URL__c = 'https://biocomposites.force.com/servlet/servlet.ImageServer?id=015U0000003Dual&oid=00DU0000000Levb',
        														Description__c = 'Test description',
        														Subtype__c = '',
        														Marketing_Resources_URL__c = 'https://biocomposites.force.com/servlet/servlet.ImageServer?id=015U0000003Dual&oid=00DU0000000Levb'
        														);
        return toiRecord;														
	}
	
	public static Community_Item_Permission_Link__c createPermissionLink(String commId, String buttonURL)
	{
		User currentUser = [Select id, Community_View__c from User where Id = :UserInfo.getUserId() limit 1];
		Community_Item_Permission_Link__c commLink = new Community_Item_Permission_Link__c(Community_Item__c = commId, Profile__c = currentUser.Community_View__c);
		if(buttonURL != '')
		{
			commLink.Button_Link_URL__c = buttonURL;
		}
		return commLink;
	}
	
	public static Community_Items__c createPublishersLibCommunityItem(String title, String authorPub, String ourView, String publishers, String abstractPub)
	{
		Id recordTypeId = [Select Id from RecordType where SObjectType='Community_Items__c' and DeveloperName='Publication_Library'].Id;
		Community_Items__c pubLibRecord = new Community_Items__c(Type__c='Publication Library', 
        														RecordTypeId = recordTypeId,
        														Title__c =  title,
        														Author__c = authorPub,
        														Our_View__c = ourView,
        														Publishers__c = publishers,
        														Abstract__c = abstractPub        														
        														);
        return pubLibRecord;														
	}
	
	public static Community_Items__c createInternalOnlyCommunityItem(String title, String altTag)
	{
		Id recordTypeId = [Select Id from RecordType where SObjectType='Community_Items__c' and DeveloperName='Left_Panel'].Id;
		Community_Items__c internalRecord = new Community_Items__c(Type__c='Internal only', 
        														RecordTypeId = recordTypeId,
        														Title__c =  title,
        													    ALT_Tag__c = altTag   														
        														);
        return internalRecord;														
	}
}