unpackaged/main/default/objects/Activity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>IF( IsTask = true, &quot;Task&quot;, &quot;Event&quot;)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Formats_Details__c.field-meta.xml
<CustomField>
    <fullName>Formats_Details__c</fullName>
    <formula>IF( I_D__c = TRUE, &quot;I&amp;D, &quot;, NULL)+
IF(  Open_Fractures__c  = TRUE, &quot;Open Fractures, &quot;, NULL)+
IF(  Voids__c  = TRUE, &quot;Voids, &quot;, NULL)+
IF( Stage_1__c  = TRUE, &quot;Stage 1, &quot;, NULL)+
IF(  Stage_2__c  = TRUE, &quot;Stage 2, &quot;, NULL)+
IF(  Other__c  = TRUE, &quot;Other, &quot;  , NULL)</formula>
    <label>Format Details</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/STIMULAN_Details__c.field-meta.xml
<CustomField>
    <fullName>STIMULAN_Details__c</fullName>
    <formula>IF(  STIMULAN_Paste__c  = TRUE, &quot;STIMULAN Paste, &quot;,Null) +
IF( STIMULAN_Beads__c  = TRUE, &quot;STIMULAN Beads, &quot;, Null)+
IF( STIMULAN_Bullets__c  = TRUE, &quot;STIMULAN Bullets&quot;,Null)</formula>
    <label>STIMULAN Details</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/STIMULAN_User__c.field-meta.xml
<CustomField>
    <fullName>STIMULAN_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>STIMULAN User</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Key_Account_Plan__c/Key_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Top 5 Account Plan</label>
    <nameField>
        <displayFormat>KAP-{000}</displayFormat>
        <label>Top 5 Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Top 5 Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Key_Account_Plan__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Key_Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Key_Account_Plan__c/fields/Total_2017_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_2017_Sales__c</fullName>
    <formula>Sales_Target__r.Total_2017_Sales__c</formula>
    <label>Previous Year Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/MBO_Activity__c/MBO_Activity__c.object-meta.xml
<CustomObject>
    <label>MBO Activity</label>
    <nameField>
        <displayFormat>MBO ACT - {000}</displayFormat>
        <label>MBO Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBO Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MBO_Activity__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/MBO_Activity__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/MBO_Activity__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MBO Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MBO_Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBO_Activity_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/Sales_by_year__c.object-meta.xml
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>H-Sales - {000}</displayFormat>
        <label>Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_by_year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q1_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q1_Sales_Actual__c</fullName>
    <label>Current Year Q1 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q1_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q1_Sales_Target__c</fullName>
    <label>Current Year Q1 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q2_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q2_Sales_Actual__c</fullName>
    <label>Current Year Q2 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q2_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q2_Sales_Target__c</fullName>
    <label>Current Year Q2 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q3_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q3_Sales_Actual__c</fullName>
    <label>Current Year Q3 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q3_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q3_Sales_Target__c</fullName>
    <label>Current Year Q3 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q4_Sales_Actual__c.field-meta.xml
<CustomField>
    <fullName>Q4_Sales_Actual__c</fullName>
    <label>Current Year Q4 Sales</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Q4_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>Q4_Sales_Target__c</fullName>
    <label>Current Year Q4 - Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Total_2017_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_2017_Sales__c</fullName>
    <formula>X2017_Q1_Actual_Sales__c +
X2017_Q2_Actual_Sales__c +
X2017_Q3_Actual_Sales__c +
X2017_Q4_Actual_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Previous Year Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Q1_Sales_Target__c +
Q2_Sales_Target__c +
Q3_Sales_Target__c +
Q4_Sales_Target__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Total_Actual__c.field-meta.xml
<CustomField>
    <fullName>Total_Actual__c</fullName>
    <formula>Q1_Sales_Actual__c +
Q2_Sales_Actual__c +
Q3_Sales_Actual__c +
Q4_Sales_Actual__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Current Year Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/X2017_Q1_Actual_Sales__c.field-meta.xml
<CustomField>
    <fullName>X2017_Q1_Actual_Sales__c</fullName>
    <label>Previous Year Q1 Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/X2017_Q2_Actual_Sales__c.field-meta.xml
<CustomField>
    <fullName>X2017_Q2_Actual_Sales__c</fullName>
    <label>Previous Year Q2 Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/X2017_Q3_Actual_Sales__c.field-meta.xml
<CustomField>
    <fullName>X2017_Q3_Actual_Sales__c</fullName>
    <label>Previous Year Q3 Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/X2017_Q4_Actual_Sales__c.field-meta.xml
<CustomField>
    <fullName>X2017_Q4_Actual_Sales__c</fullName>
    <label>Previous Year Q4 Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Sales_by_year__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
                <default>true</default>
                <label>2020</label>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/Surgeon_in_Hospital__c.object-meta.xml
<CustomObject>
    <label>Surgeon in Hospital</label>
    <nameField>
        <displayFormat>SH {0000}</displayFormat>
        <label>Surgeon in Hospital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surgeons in Hospital</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgeons</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/STIMULAN_User__c.field-meta.xml
<CustomField>
    <fullName>STIMULAN_User__c</fullName>
    <formula>Surgeon__r.STIMULAN_User__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>STIMULAN User</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/fields/Surgeon__c.field-meta.xml
<CustomField>
    <fullName>Surgeon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hospitals</relationshipLabel>
    <relationshipName>Surgeons_in_Hospital</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Surgeon_in_Hospital__c/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

unpackaged/main/default/globalValueSets/MBO_Activity_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Informal meeting (e.g. coffee chat)</fullName>
    </customValue>
    <customValue>
        <fullName>Formal presentation or department meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Meeting with hospital decision maker</fullName>
    </customValue>
    <customValue>
        <fullName>Meeting with hospital decision maker (could be procurement)</fullName>
    </customValue>
    <customValue>
        <fullName>Staff training</fullName>
    </customValue>
    <customValue>
        <fullName>First case</fullName>
    </customValue>
    <customValue>
        <fullName>Second case</fullName>
    </customValue>
    <customValue>
        <fullName>Third case</fullName>
    </customValue>
    <customValue>
        <fullName>Regular use (2 cases/month)</fullName>
    </customValue>
    <customValue>
        <fullName>External clinician presentation to target clinicians (for example KOL dinner presentation)</fullName>
        <label>External clinician presentation to target clinicians (e.g. KOL dinner presentation)</label>
    </customValue>
    <customValue>
        <fullName>Target clinician presents internally</fullName>
    </customValue>
    <customValue>
        <fullName>Target clinician presents externally</fullName>
    </customValue>
    <customValue>
        <fullName>Case study write-up</fullName>
    </customValue>
    <customValue>
        <fullName>Poster presentation</fullName>
    </customValue>
    <customValue>
        <fullName>Podium presentation</fullName>
    </customValue>
    <customValue>
        <fullName>Article published</fullName>
    </customValue>
    <customValue>
        <fullName>Product presentation to surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Dry26 presentation to surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Product presentation to other</fullName>
    </customValue>
    <customValue>
        <fullName>Scientific exchange with surgeons</fullName>
    </customValue>
    <customValue>
        <fullName>Grand rounds/journal club/resident day</fullName>
    </customValue>
    <customValue>
        <fullName>Informal chat with surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Cover case</fullName>
    </customValue>
    <customValue>
        <fullName>Surgeon – 1st case</fullName>
    </customValue>
    <customValue>
        <fullName>Surgeon – 2nd case</fullName>
    </customValue>
    <customValue>
        <fullName>Surgeon – 3rd case</fullName>
    </customValue>
    <customValue>
        <fullName>In-service training</fullName>
    </customValue>
    <customValue>
        <fullName>Structured rep training</fullName>
    </customValue>
    <customValue>
        <fullName>DRy26 rep training</fullName>
    </customValue>
    <customValue>
        <fullName>CE seminar</fullName>
    </customValue>
    <masterLabel>MBO Activity Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountPanelsClass.cls
public class AccountPanelsClass {

  // the record id
  @TestVisible private Key_Account_Plan__c record { get; set; }
  // the KAP's related Account id
  @TestVisible private String accountId { get; set; }
  // the KAP's related Sales_by_year__c record
  public List<Sales_by_year__c> sale { get; set; }
  // the KAP's Account's related Surgeons (Contact, via Person Accounts)
  @TestVisible private List<Contact> surgeons { get; set; }
  // the KAP's Account's related MBO_Activity__c
  @TestVisible private List<MBO_Activity__c> activity { get; set; }

  // constructor
  public AccountPanelsClass(ApexPages.StandardController controller) {
    // get KAP record
    record = (Key_Account_Plan__c)controller.getRecord();
    // get related Hospital (Account, via Person Accounts)
    accountId = getAccountId();
    System.debug('accountId:  '+accountId);
    // get related Sales_by_year__c
    // should only ever be one, only one record should be set to Active__c
    sale = getSale();
    // Surgeons linked to a hospital by the junction object Surgeon_in_Hospital__c
    surgeons = getSurgeons();
    // get related activity for the KAP's Account
    // restrict to the last 30 days
    activity = getActivity();
  }
    
  // get the account for the current record
  public String getAccountId() {
    String accountId = '';
    List<Key_Account_Plan__c> accounts = new List<Key_Account_Plan__c>();
     accounts = [
      SELECT Hospital__c 
      FROM Key_Account_Plan__c
      WHERE Id =: record.Id
      LIMIT 1
    ];
    if(accounts != null && accounts.size() > 0)
      accountId = accounts[0].Hospital__c;
    return accountId;
  }
    
  // get the sales for the current record's account
  public List<Sales_by_year__c> getSale() {      
    List<Sales_by_year__c> saleList = new List<Sales_by_year__c>();
    if(accountId != null && accountId != '') {
      saleList = [
        SELECT Q1_Sales_Actual__c, Q1_Sales_Target__c, Q2_Sales_Actual__c,
        Q2_Sales_Target__c, Q3_Sales_Actual__c, Q3_Sales_Target__c,
        Q4_Sales_Actual__c, Q4_Sales_Target__c, Year__c, X2017_Q1_Actual_Sales__c,
        X2017_Q2_Actual_Sales__c, X2017_Q3_Actual_Sales__c, X2017_Q4_Actual_Sales__c,
        Total_2017_Sales__c, Total_Actual__c, Total__c
        FROM Sales_by_year__c
        WHERE Active__c = true
        AND Account__c =: accountId
        LIMIT 1
      ];
    }
    return saleList;
  }
    
  // get the surgeons for the current record's account
  public List<Contact> getSurgeons() {
    List<Surgeon_in_Hospital__c> surgeonIds = new List<Surgeon_in_Hospital__c>();
    if(accountId != null && accountId != '') {
      surgeonIds =  [
        SELECT Surgeon__c
        FROM Surgeon_in_Hospital__c 
        WHERE Hospital__c =: accountId
      ];
    }
    // for each Surgeon, get their Ids
    List<Id> ids = new List<Id>();
    for (Integer i = 0; i < surgeonIds.size(); i++) {
      if (surgeonIds[i].Surgeon__c != null) {
        ids.add(surgeonIds[i].Surgeon__c);
      }
    }
    // finally get all fields for Surgeons we now know are related to the KAP
    List<Contact> surgeons = new List<Contact>();
    if(ids != null && ids.size() > 0) {
      surgeons =  [
        SELECT Id, CreatedDate, Name,
          Formats_Details__c, STIMULAN_Details__c, STIMULAN_User__c
        FROM Contact
        WHERE Id IN: ids
      ];
    }
    return surgeons;
  }
    
  // get the activity for the current record's account
  public List<MBO_Activity__c> getActivity() {
    List<MBO_Activity__c> activity = new List<MBO_Activity__c>();
    activity = [
      SELECT Name, Date__c, Type__c, Details__c
      FROM MBO_Activity__c
      WHERE Surgeon__c =: accountId
      AND Date__c <= LAST_N_DAYS:91
    ];
    return activity;
  }
  
}